### PR TITLE
[16.0][ADD] edi_partner_oca

### PR DESCRIPTION
**Pull request by QuocDuong1306**
This module intends to create a base to be extended by local edi rules for partner

Include:
- #52

### CODE REVIEW

**Review by santostelmo — APPROVED** [review]

**Review by simahawk — COMMENTED** [review]
LG but https://github.com/OCA/edi-framework/pull/52 needs fixes

**Comment by QuocDuong1306** [comment]
Thanks, I updated

**Review by simahawk — COMMENTED** [review]
to be rebased

**Comment by QuocDuong1306** [comment]
Thank @simahawk , I updated

**Review by simahawk — APPROVED** [review]

**Pull request merged**
