### PR TITLE
[17.0][MIG] edi_webservice_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by john-herholz-dt**

### CODE REVIEW

**Comment by gurneyalex** [comment]
Please check https://github.com/OCA/edi-framework/pull/72  which adds on 16.0 some left out commits from the 15.0 branch.

**Comment by john-herholz-dt** [comment]
Thanks @gurneyalex for letting me know. I have re-done the migration with the missing commits from your PR.

**Comment by SilvioC2C** [comment]
@john-herholz-dt tests are failing, would you be able to take a look?

**Comment by SilvioC2C** [comment]
@john-herholz-dt I've opened #123 to be able to trigger the tests and see what was failing; turns out, this is the only thing that was missing:
https://github.com/OCA/edi-framework/pull/123/commits/499ef8a229919eca0641d5243885a158bc00b077

Feel free to choose whether you prefer to update this PR and I'll close mine, or the other way around :smile:

**Comment by john-herholz-dt** [comment]
@SilvioC2C I''ll close mine, as I have currently no time for it. Thanks for investigating!

**Pull request closed without merging**
