### PR TITLE
[16.0][FIX] edi_oca: consider parent record when checking access rule

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
This fix prevents an error raised when you have child exchanges that do not have a specific model and res_id assigned.

When getting the related record of a child we are already looking at the parent if the exchange record does not have a specific model set (https://github.com/OCA/edi-framework/blob/d484f0dcbb7b1caca1aaae0f9a3c2b3510a714f5/edi_oca/models/edi_exchange_record.py#L210). The same should be done when checking the access.

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
@etobella @simahawk could you review this one? :)

**Review by simahawk — COMMENTED** [review]
LG... any chance to have a test?

**Comment by JordiMForgeFlow** [comment]
@simahawk done :)

**Review by simahawk — APPROVED** [review]

**Pull request merged**
