### PR TITLE
 [16.0][MIG] edi_endpoint_oca

### PR DESCRIPTION
**Pull request by simahawk**
Replaces  #7, restore the origin field, fixes pre-commit.

### CODE REVIEW

**Comment by simahawk** [comment]
I'm checking the build

**Comment by simahawk** [comment]
current findings: if any of `edi_account_oca` or `edi_product_oca` is installed, it breaks.

**Comment by simahawk** [comment]
@nilshamerlinck can you drop a review?

**Review by nilshamerlinck — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
