### PR TITLE
[16.0][PORT] edi_oca: Port edi_oca from edi/14.0

### PR DESCRIPTION
**Pull request by QuocDuong1306**
Port from PRs:
- https://github.com/OCA/edi/pull/808
- https://github.com/OCA/edi/pull/819
- https://github.com/OCA/edi/pull/822
- https://github.com/OCA/edi/pull/824
- https://github.com/OCA/edi/pull/830
- https://github.com/OCA/edi/pull/852
- https://github.com/OCA/edi/pull/855
- https://github.com/OCA/edi/pull/796
- https://github.com/OCA/edi/pull/880
- https://github.com/OCA/edi/pull/897

### CODE REVIEW

**Comment by simahawk** [comment]
The change to `edi_exchange_template` should be excluded. 
Can you also update the blacklist file at the end? https://github.com/OCA/edi-framework/blob/16.0/.oca/oca-port/blacklist/edi_oca.json

**Comment by QuocDuong1306** [comment]
Hello @simahawk , [this commit](https://github.com/OCA/edi/pull/855/commits/c2ff53fec3ded054b47067035d0df6b0087b1966) will help to fix the test

**Comment by QuocDuong1306** [comment]
Hello @simahawk , I created PR https://github.com/OCA/edi-framework/pull/63 on top of this one to include the forward-ports for `edi_exchange_template_oca` as well

**Comment by nilshamerlinck** [comment]
This PR can be ignored in favor of https://github.com/OCA/edi-framework/pull/63

**Pull request closed without merging**
