### PR TITLE
[16.0][FIX] edi_oca: do not try to automatically re-process input_processed_error records

### PR DESCRIPTION
**Pull request by nilshamerlinck**
- scheduled action "EDI exchange check input sync" will currently create `action_exchange_process` jobs for any record in state "input_processed_error"
- this does not make any sense, as such records failed to process because of ["swallable"](https://github.com/OCA/edi-framework/blob/16.0/edi_oca/models/edi_backend.py#L490) exceptions, that should be considered as final

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
makes sense, but I'd like to see a test :wink:

**Comment by QuocDuong1306** [comment]
Hello @simahawk @nilshamerlinck , I added a test and rebased also

**Review by simahawk — APPROVED** [review]
LGTM. @etobella WDYT?

We should back/fwd port this when ready.

**Review by etobella — APPROVED** [review]

**Comment by simahawk** [comment]
/ocabot merge patch

@nilshamerlinck would you mind fwd/back porting? :pray:

**Pull request merged**
