### PR TITLE
[MIG] edi_oca: Migration to 16.0, moved from edi repository

### PR DESCRIPTION
**Pull request by john-herholz-dt**
Regarding original PR 749 from edi repository:

- I also removed v15 code which is not used anymore
- Replaced 'import mock' with 'from unittest import mock'

### CODE REVIEW

**Comment by john-herholz-dt** [comment]
@simahawk I moved the module but the tests timeout here as well and I don't know why.

**Comment by simahawk** [comment]
@john-herholz-dt thanks for your work and your patience :)
I've triggered the build again, let's see...

**Comment by simahawk** [comment]
@john-herholz-dt can you push again to trigger another build pls?

**Comment by john-herholz-dt** [comment]
@simahawk I might be able to do so later today, but I re-triggered it in the other repo already 5-6 times and always a timeout after 360 min.
But I will try again later.
Cheers

**Comment by john-herholz-dt** [comment]
tests failed again, any idea?

**Comment by simahawk** [comment]
Closing in favor of https://github.com/OCA/edi-framework/pull/5

**Pull request closed without merging**
