### PR TITLE
[17.0][MIG] edi_account_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 157027
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/edi-framework/issues/38

Depends on:

- [edi_oca] https://github.com/OCA/edi-framework/pull/47

### CODE REVIEW

**Review by miquelpascual — APPROVED** [review]
LGTM

**Review by lbarry-apsl — APPROVED** [review]
Reviewed on the Runboat

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Comment by HaraldPanten** [comment]
@etobella We will work in the migration of l10n_es_facturae_face (Spanish location), but we're waiting for some dependencies (one of them is this PR).

Could you have a look in order to move forward?

We've validated it technically.

THX!

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
