### PR TITLE
[17.0][MIG] edi_webservice_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by SilvioC2C**
Supersedes #69

### CODE REVIEW

**Review by john-herholz-dt — APPROVED** [review]

**Review by yankinmax — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by john-herholz-dt** [comment]
@SilvioC2C are you using this module already? I cannot get past the user error in components/send.py:

```
raise exceptions.UserError(
    _("`method` is required in `webservice` type settings.")
) from err
```

Currently there is - as far as I see it - no way that the component gets the webservice dict from the advanced exchange type settings.

**Comment by SilvioC2C** [comment]
@john-herholz-dt yes, already in use.

I can share with you an example of the `.xml` file with the `edi.exchange.type` record's field `advanced_settings_edit`:
```
        <field name="advanced_settings_edit">
components:
    send:
        usage: webservice.send
        work_ctx:
            webservice:
                method: post
                kwargs:
                    url_params:
                        path: some/path
        </field>
```

EDIT: the result you get from this snippet when reaching the try/except block you quoted:
```
>>> self.ws_settings
{'method': 'post', 'kwargs': {'url_params': {'path': 'some/path'}}}
>>> method = self.ws_settings["method"].lower()
>>> method
'post'
```

**Comment by john-herholz-dt** [comment]
Thanks that was it!

**Comment by SilvioC2C** [comment]
You're welcome! I've been struggling with it myself, so no worries. Maybe I'll add it in the docs if I have time...

**Pull request merged**
