### PR TITLE
[16.0][MIG] edi_account_invoice_import

### PR DESCRIPTION
**Pull request by EvaSForgeFlow**
Correcting tests.

Depends on #5 and https://github.com/OCA/edi/pull/753

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
rebased

**Comment by gurneyalex** [comment]
hello @EvaSForgeFlow what is the status of this pull request?

**Comment by LoisRForgeFlow** [comment]
Hi @gurneyalex 

Eva is now longer working with us. Feel free to supersede this PR, we don't have plans to finish it in the short term.

Regards,

**Comment by gurneyalex** [comment]
Thanks for the super fast feedback @LoisRForgeFlow 

I'll close this PR and restart from where you left it :green_heart:

**Comment by gurneyalex** [comment]
Moved to https://github.com/OCA/edi-framework/pull/67

**Pull request closed without merging**
